name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: sh ./configure.sh
    - name: build
      run: make
    - name: unit test
      run: sh ./runutest.sh
